### ISSUE TITLE
Error on execute

### ISSUE THREAD

**Issue by ribafs** [azeemhassni/simplest-php-router#1]
Thank you for colaborate.
When I execute appear:
Notice: Undefined index: rotas in /backup/www/rotas/router.php on line 32
Warning: call_user_func() expects parameter 1 to be a valid callback, no array or string given in /backup/www/rotas/router.php on line 34

**Comment by azeemhassni** [comment]
Could you show me some code?

**Comment by ribafs** [comment]
Thank you.
When I call index.php appear:

![image](https://user-images.githubusercontent.com/855200/62227927-28590d80-b393-11e9-8704-e65ecc52d8cd.png)

Error in line 32 of router.php

**Comment by azeemhassni** [comment]
I meant the code you wrote to register your routes.

**Comment by ribafs** [comment]
I use only your code:
```php
<?php
require_once "router.php";
route('/', function () {
    return "Hello World";
});
route('/about', function () {
    return "Hello form the about route";
});
$action = $_SERVER['REQUEST_URI'];
dispatch($action);
```
